"""Add RAG Tools tables

Revision ID: 1dc18da334bf
Revises: 490f1d4dcd0e
Create Date: 2024-10-09 23:53:32.533995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc18da334bf'
down_revision: Union[str, None] = '490f1d4dcd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
