"""Create a baseline migrations

Revision ID: 490f1d4dcd0e
Revises: 
Create Date: 2024-10-09 23:50:15.864704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490f1d4dcd0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pg_search_tool')
    op.drop_table('documents_fadhil')
    op.drop_table('llm')
    op.drop_table('vectordb')
    op.drop_table('embedder')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedder',
    sa.Column('embedder_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('embedder_id', name='embedder_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('vectordb',
    sa.Column('vectordb_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('collection_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dir_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_allow_reset', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('vectordb_id', name='vectordb_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('llm',
    sa.Column('llm_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('llm_id', name='llm_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('documents_fadhil',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='documents_fadhil_pkey')
    )
    op.create_table('pg_search_tool',
    sa.Column('tool_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('llm_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedder_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('vectordb_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['embedder_id'], ['embedder.embedder_id'], name='pg_search_tool_embedder_id_fkey'),
    sa.ForeignKeyConstraint(['llm_id'], ['llm.llm_id'], name='pg_search_tool_llm_id_fkey'),
    sa.ForeignKeyConstraint(['vectordb_id'], ['vectordb.vectordb_id'], name='pg_search_tool_vectordb_id_fkey'),
    sa.PrimaryKeyConstraint('tool_id', name='pg_search_tool_pkey')
    )
    # ### end Alembic commands ###
